CREATE TABLE [dbo].[tbcajeros] (
    [ID_CAJERO]            INT           IDENTITY (1, 1) NOT NULL,
    [CAJERO_ID]            INT           NOT NULL,
    [NOMBRE]               VARCHAR (100) NOT NULL,
    [USUARIO]              VARCHAR (31)  NOT NULL,
    [OPERAR_CAJAS]         CHAR (1)      DEFAULT ('N') NOT NULL,
    [ABRIR_CAJAS]          CHAR (1)      DEFAULT ('N') NOT NULL,
    [REPORTES_DEL_DIA]     CHAR (1)      DEFAULT ('C') NOT NULL,
    [USUARIO_CREADOR]      VARCHAR (31)  DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]  DATETIME      NOT NULL,
    [USUARIO_AUT_CREACION] VARCHAR (31)  DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]    VARCHAR (31)  DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF] DATETIME      NOT NULL,
    [USUARIO_AUT_MODIF]    VARCHAR (31)  DEFAULT (NULL) NULL,
    [FECHA_REGISTRO]       DATETIME      DEFAULT (NULL) NULL,
    CONSTRAINT [Ph_IdCajeros] PRIMARY KEY CLUSTERED ([ID_CAJERO] ASC),
    CONSTRAINT [CAJEROS_AK1] UNIQUE NONCLUSTERED ([USUARIO] ASC)
);

