CREATE TABLE [dbo].[tbcajas] (
    [ID_CAJA]               INT          IDENTITY (1, 1) NOT NULL,
    [CAJA_ID]               INT          NOT NULL,
    [NOMBRE]                VARCHAR (50) NOT NULL,
    [ALMACEN_ID]            INT          NOT NULL,
    [MODIFICAR_ALMACEN]     CHAR (1)     DEFAULT ('S') NOT NULL,
    [VENTAS_DESDE]          CHAR (1)     DEFAULT ('A') NULL,
    [PERMITE_COBRAR]        CHAR (1)     DEFAULT ('S') NULL,
    [FORMA_COBRO_PREDET_ID] INT          DEFAULT (NULL) NULL,
    [IMAGENES_CAJA_ID]      INT          DEFAULT (NULL) NULL,
    [MANEJAR_VENDEDORES]    CHAR (1)     DEFAULT ('S') NOT NULL,
    [USUARIO_CREADOR]       VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]   DATETIME     NOT NULL,
    [USUARIO_AUT_CREACION]  VARCHAR (31) DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]     VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF]  DATETIME     NOT NULL,
    [USUARIO_AUT_MODIF]     VARCHAR (31) DEFAULT (NULL) NULL,
    [ID_ALMACEN]            INT          NOT NULL,
    [FECHA_REGISTRO]        DATETIME     DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdCaja] PRIMARY KEY CLUSTERED ([ID_CAJA] ASC),
    CONSTRAINT [CAJAS_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [ALMACENES_A_CAJAS_idx]
    ON [dbo].[tbcajas]([ID_ALMACEN] ASC);

