CREATE TABLE [dbo].[tbclaves_proveedores] (
    [ID_CVE_PROV]       INT          IDENTITY (1, 1) NOT NULL,
    [CLAVE_PROV_ID]     INT          NOT NULL,
    [CLAVE_PROV]        VARCHAR (20) NOT NULL,
    [PROVEEDOR_ID]      INT          NOT NULL,
    [ROL_CLAVE_PROV_ID] INT          NOT NULL,
    CONSTRAINT [Pk_IdCveProv] PRIMARY KEY CLUSTERED ([ID_CVE_PROV] ASC),
    CONSTRAINT [CLAVES_PROVEEDORES_AK1] UNIQUE NONCLUSTERED ([CLAVE_PROV] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CLAVES_PROVEEDORES_AK2]
    ON [dbo].[tbclaves_proveedores]([PROVEEDOR_ID] ASC, [CLAVE_PROV] ASC);

