CREATE TABLE [dbo].[tbclaves_clientes] (
    [ID_CVE_CLI]       INT          IDENTITY (1, 1) NOT NULL,
    [CLAVE_CLIENTE_ID] INT          NOT NULL,
    [CLAVE_CLIENTE]    VARCHAR (20) NOT NULL,
    [CLIENTE_ID]       INT          NOT NULL,
    [ROL_CLAVE_CLI_ID] INT          NOT NULL,
    CONSTRAINT [Pk_IdCveCli] PRIMARY KEY CLUSTERED ([ID_CVE_CLI] ASC),
    CONSTRAINT [CLAVES_CLIENTES_AK1] UNIQUE NONCLUSTERED ([ID_CVE_CLI] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CLAVES_CLIENTES_AK2]
    ON [dbo].[tbclaves_clientes]([CLIENTE_ID] ASC, [ID_CVE_CLI] ASC);

