CREATE TABLE [dbo].[tbclaves_cat_sec] (
    [NOMBRE_TABLA] VARCHAR (31) NOT NULL,
    [ELEM_ID]      INT          NOT NULL,
    [CLAVE]        VARCHAR (20) NOT NULL,
    CONSTRAINT [Pk_Claves_Cat_Sec] PRIMARY KEY CLUSTERED ([NOMBRE_TABLA] ASC, [ELEM_ID] ASC),
    CONSTRAINT [CLAVES_CAT_SEC_AK1] UNIQUE NONCLUSTERED ([NOMBRE_TABLA] ASC, [CLAVE] ASC)
);

