CREATE TABLE [dbo].[tbclaves_articulos] (
    [ID_CVE_ART]        INT          IDENTITY (1, 1) NOT NULL,
    [CLAVE_ARTICULO_ID] INT          NOT NULL,
    [CLAVE_ARTICULO]    VARCHAR (20) NOT NULL,
    [ARTICULO_ID]       INT          NOT NULL,
    [ROL_CLAVE_ART_ID]  INT          NOT NULL,
    CONSTRAINT [Pk_IdCveArt] PRIMARY KEY CLUSTERED ([ID_CVE_ART] ASC),
    CONSTRAINT [CLAVES_ARTICULOS_AK1] UNIQUE NONCLUSTERED ([CLAVE_ARTICULO] ASC)
);


GO
CREATE NONCLUSTERED INDEX [CLAVES_ARTICULOS_AK2]
    ON [dbo].[tbclaves_articulos]([ARTICULO_ID] ASC, [CLAVE_ARTICULO] ASC);

