CREATE TABLE [dbo].[tbcobradores] (
    [ID_COBRADOR]           INT           IDENTITY (1, 1) NOT NULL,
    [COBRADOR_ID]           INT           NOT NULL,
    [NOMBRE]                VARCHAR (100) NOT NULL,
    [POLITICA_COMIS_COB_ID] INT           NOT NULL,
    [ES_PREDET]             CHAR (1)      DEFAULT ('N') NULL,
    [USUARIO_CREADOR]       VARCHAR (31)  DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]   DATETIME      NOT NULL,
    [USUARIO_AUT_CREACION]  VARCHAR (31)  DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]     VARCHAR (31)  DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF]  DATETIME      NOT NULL,
    [USUARIO_AUT_MODIF]     VARCHAR (31)  DEFAULT (NULL) NULL,
    [FECHA_REGISTRO]        DATETIME      DEFAULT (NULL) NULL,
    [ID_POLITICA_COMIS_COB] INT           NOT NULL,
    CONSTRAINT [Pk_IdCobrador] PRIMARY KEY CLUSTERED ([ID_COBRADOR] ASC),
    CONSTRAINT [COBRADORES_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [POLITICAS_A_COB_idx]
    ON [dbo].[tbcobradores]([ID_POLITICA_COMIS_COB] ASC);

