CREATE TABLE [dbo].[tbdoctos_pv] (
    [DOCTO_PV_ID]         INT             IDENTITY (1, 1) NOT NULL,
    [CAJA_ID]             INT             DEFAULT (NULL) NULL,
    [TIPO_DOCTO]          CHAR (1)        DEFAULT (NULL) NULL,
    [FOLIO]               VARCHAR (9)     DEFAULT (NULL) NULL,
    [FECHA]               DATE            DEFAULT (NULL) NULL,
    [HORA]                TIME (7)        DEFAULT (NULL) NULL,
    [CAJERO_ID]           INT             DEFAULT (NULL) NULL,
    [CLIENTE_ID]          INT             DEFAULT (NULL) NULL,
    [DIR_CLI_ID]          INT             DEFAULT (NULL) NULL,
    [ALMACEN_ID]          INT             DEFAULT (NULL) NULL,
    [MONEDA_ID]           INT             DEFAULT (NULL) NULL,
    [TIPO_CAMBIO]         DECIMAL (18, 6) DEFAULT (NULL) NULL,
    [DSCTO_PCTJE]         DECIMAL (9, 6)  DEFAULT (NULL) NULL,
    [DSCTO_IMPORTE]       DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [ESTATUS]             CHAR (1)        DEFAULT (NULL) NULL,
    [APLICADO]            CHAR (1)        DEFAULT (NULL) NULL,
    [IMPORTE_NET]         DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [TOTAL_IMPUESTPS]     DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [IMPORTE_DONATIVO]    DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [TOTAL_FPGC]          DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [SISTEMA_ORIGEN]      CHAR (2)        DEFAULT (NULL) NULL,
    [VENDEDOR_ID]         INT             DEFAULT (NULL) NULL,
    [ES_CFD]              CHAR (1)        DEFAULT (NULL) NULL,
    [ENVIADO]             CHAR (1)        DEFAULT (NULL) NULL,
    [USUARIO_CREADOR]     VARCHAR (31)    DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION] DATETIME        DEFAULT (NULL) NULL,
    [TIPO_DSCTO]          CHAR (1)        DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_DoctoPvId] PRIMARY KEY CLUSTERED ([DOCTO_PV_ID] ASC)
);

