CREATE TABLE [dbo].[tbdoctos_ve_det] (
    [DOCTO_VE_DET_ID]   INT             IDENTITY (1, 1) NOT NULL,
    [DOCTO_VE_ID]       INT             DEFAULT (NULL) NULL,
    [CLAVE_ARTICULO]    VARCHAR (20)    DEFAULT (NULL) NULL,
    [ARTICULO_ID]       INT             DEFAULT (NULL) NULL,
    [UNIDADES]          DECIMAL (18, 5) DEFAULT (NULL) NULL,
    [PRECIO_UNITARIO]   DECIMAL (18, 6) DEFAULT (NULL) NULL,
    [PCTJE_DSCTO]       DECIMAL (9, 6)  DEFAULT (NULL) NULL,
    [PCTJE_DSCTO_VOL]   DECIMAL (9, 6)  DEFAULT (NULL) NULL,
    [PCTJE_DSCTO_PROMO] DECIMAL (9, 6)  DEFAULT (NULL) NULL,
    [PRECIO_TOTAL_NETO] DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [POSICION]          INT             DEFAULT (NULL) NULL,
    [NOTAS]             TEXT            NULL,
    CONSTRAINT [Pk_DoctoVeDetId] PRIMARY KEY CLUSTERED ([DOCTO_VE_DET_ID] ASC)
);

