CREATE TABLE [dbo].[tbdoctos_ve] (
    [DOCTO_VE_ID]            INT             IDENTITY (1, 1) NOT NULL,
    [TIPO_DOCTO]             CHAR (1)        DEFAULT (NULL) NULL,
    [FOLIO]                  VARCHAR (9)     DEFAULT (NULL) NULL,
    [FECHA]                  DATETIME        DEFAULT (NULL) NULL,
    [CLIENTE_ID]             INT             DEFAULT (NULL) NULL,
    [DIR_CLI_ID]             INT             DEFAULT (NULL) NULL,
    [DIR_CONSIG_ID]          INT             DEFAULT (NULL) NULL,
    [ALMACEN_ID]             INT             DEFAULT (NULL) NULL,
    [MONEDA_ID]              INT             DEFAULT (NULL) NULL,
    [TIPO_CAMBIO]            DECIMAL (18, 6) DEFAULT (NULL) NULL,
    [DSCTO_PCTJE]            DECIMAL (9, 6)  DEFAULT (NULL) NULL,
    [DSCTO_IMPORTE]          DECIMAL (9, 6)  DEFAULT (NULL) NULL,
    [ESTATUS]                CHAR (1)        DEFAULT (NULL) NULL,
    [APLICADO]               CHAR (1)        DEFAULT (NULL) NULL,
    [IMPORTE_NETO]           DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [FLETES]                 DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [OTROS_CARGOS]           DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [TOTAL_IMPUESTOS]        DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [TOTAL_RETENCIONES]      DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [TOTAL_FPGC]             DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [PESO_EMBARQUE]          DECIMAL (12, 3) DEFAULT (NULL) NULL,
    [SISTEMA_ORIGEN]         CHAR (2)        DEFAULT (NULL) NULL,
    [COND_PAGO_ID]           INT             DEFAULT (NULL) NULL,
    [PCTJE_DSCTO_PPAG]       DECIMAL (9, 6)  DEFAULT (NULL) NULL,
    [VENDEDOR_ID]            INT             DEFAULT (NULL) NULL,
    [PCTJE_COMIS]            DECIMAL (9, 6)  DEFAULT (NULL) NULL,
    [IMPORTE_COBRO]          DECIMAL (15, 2) DEFAULT (NULL) NULL,
    [ES_CFD]                 CHAR (1)        DEFAULT (NULL) NULL,
    [ENVIADO]                CHAR (1)        DEFAULT (NULL) NULL,
    [CARGAR_SUN]             CHAR (1)        DEFAULT (NULL) NULL,
    [TIPO_DSCTO]             CHAR (1)        DEFAULT (NULL) NULL,
    [FECHA_VIGENCIA_ENTREGA] DATETIME        DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_DoctoVeId] PRIMARY KEY CLUSTERED ([DOCTO_VE_ID] ASC)
);

