CREATE TABLE [dbo].[tbdsctos_max_lineas] (
    [ID_DSCTO_MAX_LIN]         INT            IDENTITY (1, 1) NOT NULL,
    [DSCTO_MAX_LINEA_ID]       INT            NOT NULL,
    [POLITICA_DSCTO_MAXIMO_ID] INT            NOT NULL,
    [LINEA_ARTICULO_ID]        INT            NOT NULL,
    [DESCUENTO_MAXIMO]         DECIMAL (9, 6) DEFAULT ('0.000000') NOT NULL,
    CONSTRAINT [Pk_IdDsctoMaxLin] PRIMARY KEY CLUSTERED ([ID_DSCTO_MAX_LIN] ASC),
    CONSTRAINT [DSCTOS_MAX_LINEAS_AK1] UNIQUE NONCLUSTERED ([POLITICA_DSCTO_MAXIMO_ID] ASC, [LINEA_ARTICULO_ID] ASC)
);

