CREATE TABLE [dbo].[tbdsctos_vol_lineas] (
    [ID_DSCTOS_VOL_LIN]         INT             IDENTITY (1, 1) NOT NULL,
    [DSCTO_VOL_LINEA_ID]        INT             NOT NULL,
    [POLITICA_DSCTO_VOLUMEN_ID] INT             NOT NULL,
    [LINEA_ARTICULO_ID]         INT             NOT NULL,
    [UNIDADES]                  DECIMAL (18, 5) DEFAULT ('0.00000') NOT NULL,
    [DESCUENTO]                 DECIMAL (9, 6)  DEFAULT ('0.000000') NOT NULL,
    CONSTRAINT [Pk_IdDsctoVolLin] PRIMARY KEY CLUSTERED ([ID_DSCTOS_VOL_LIN] ASC),
    CONSTRAINT [DSCTOS_VOL_LINEAS_AK1] UNIQUE NONCLUSTERED ([POLITICA_DSCTO_VOLUMEN_ID] ASC, [LINEA_ARTICULO_ID] ASC, [UNIDADES] ASC)
);

