CREATE TABLE [dbo].[tbdsctos_promo_arts] (
    [ID_DSCTO_PROMO_ART]      INT            IDENTITY (1, 1) NOT NULL,
    [DSCTO_PROMO_ART_ID]      INT            NOT NULL,
    [POLITICA_DSCTO_PROMO_ID] INT            NOT NULL,
    [CLAVE_ARTICULO]          VARCHAR (20)   DEFAULT (NULL) NULL,
    [ARTICULO_ID]             INT            NOT NULL,
    [DESCUENTO]               DECIMAL (9, 6) DEFAULT ('0.000000') NOT NULL,
    CONSTRAINT [Pk_IdDsctoPromoArt] PRIMARY KEY CLUSTERED ([ID_DSCTO_PROMO_ART] ASC),
    CONSTRAINT [DSCTOS_PROMO_ARTS_AK1] UNIQUE NONCLUSTERED ([POLITICA_DSCTO_PROMO_ID] ASC, [ARTICULO_ID] ASC)
);

