CREATE TABLE [dbo].[tbdsctos_max_arts] (
    [ID_DSCTO_MAX_ART]         INT            IDENTITY (1, 1) NOT NULL,
    [DSCTO_MAX_ART_ID]         INT            NOT NULL,
    [POLITICA_DSCTO_MAXIMO_ID] INT            NOT NULL,
    [CLAVE_ARTICULO]           VARCHAR (20)   DEFAULT (NULL) NULL,
    [ARTICULO_ID]              INT            NOT NULL,
    [DESCUENTO_MAXIMO]         DECIMAL (9, 6) DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdDsctoMaxArt] PRIMARY KEY CLUSTERED ([ID_DSCTO_MAX_ART] ASC),
    CONSTRAINT [DSCTOS_MAX_ARTS_AK1] UNIQUE NONCLUSTERED ([POLITICA_DSCTO_MAXIMO_ID] ASC, [ARTICULO_ID] ASC)
);

