CREATE TABLE [dbo].[tbdsctos_artcli_lineas] (
    [ID_DSCTO_ARTCLI_LIN]       INT            IDENTITY (1, 1) NOT NULL,
    [DSCTO_ARTCLI_LINEA_ID]     INT            NOT NULL,
    [POLITICA_DSCTO_ART_CLI_ID] INT            NOT NULL,
    [LINEA_ARTICULO_ID]         INT            NOT NULL,
    [DESCUENTO]                 DECIMAL (9, 6) DEFAULT ('0.000000') NOT NULL,
    CONSTRAINT [Pk_IdDsctoArtCliLin] PRIMARY KEY CLUSTERED ([ID_DSCTO_ARTCLI_LIN] ASC),
    CONSTRAINT [DSCTOS_ARTCLI_LINEAS_AK1] UNIQUE NONCLUSTERED ([POLITICA_DSCTO_ART_CLI_ID] ASC, [LINEA_ARTICULO_ID] ASC)
);

