CREATE TABLE [dbo].[tbdsctos_artcli_grupos] (
    [ID_DSCTO_ARTCLI_GPO]       INT            IDENTITY (1, 1) NOT NULL,
    [DSCTO_ARTCLI_GRUPO_ID]     INT            NOT NULL,
    [POLITICA_DSCTO_ART_CLI_ID] INT            NOT NULL,
    [GRUPO_LINEA_ID]            INT            NOT NULL,
    [DESCUENTO]                 DECIMAL (9, 6) DEFAULT ('0.000000') NOT NULL,
    CONSTRAINT [Pk_IdDsctoArtCliGpo] PRIMARY KEY CLUSTERED ([ID_DSCTO_ARTCLI_GPO] ASC),
    CONSTRAINT [DSCTOS_ARTCLI_GRUPOS_AK1] UNIQUE NONCLUSTERED ([POLITICA_DSCTO_ART_CLI_ID] ASC, [GRUPO_LINEA_ID] ASC)
);

