CREATE TABLE [dbo].[tbdsctos_vol_globales] (
    [ID_DSCTO_VOL_GBL]          INT             IDENTITY (1, 1) NOT NULL,
    [DSCTO_VOL_GLOBAL_ID]       INT             NOT NULL,
    [POLITICA_DSCTO_VOLUMEN_ID] INT             NOT NULL,
    [UNIDADES]                  DECIMAL (18, 5) DEFAULT ('0.00000') NOT NULL,
    [DESCUENTO]                 DECIMAL (9, 6)  DEFAULT ('0.000000') NOT NULL,
    CONSTRAINT [Pk_IdDsctoVolGbl] PRIMARY KEY CLUSTERED ([ID_DSCTO_VOL_GBL] ASC),
    CONSTRAINT [DSCTOS_VOL_GLOBALES_AK1] UNIQUE NONCLUSTERED ([POLITICA_DSCTO_VOLUMEN_ID] ASC, [UNIDADES] ASC)
);

