CREATE TABLE [dbo].[tbdsctos_promo_lineas] (
    [ID_DSCTO_PROMO_LIN]      INT            IDENTITY (1, 1) NOT NULL,
    [DSCTO_PROMO_LINEA_ID]    INT            NOT NULL,
    [POLITICA_DSCTO_PROMO_ID] INT            NOT NULL,
    [LINEA_ARTICULO_ID]       INT            NOT NULL,
    [DESCUENTO]               DECIMAL (9, 6) DEFAULT ('0.000000') NOT NULL,
    CONSTRAINT [Pk_IdDsctoPromoLin] PRIMARY KEY CLUSTERED ([ID_DSCTO_PROMO_LIN] ASC),
    CONSTRAINT [DSCTOS_PROMO_LINEAS_AK1] UNIQUE NONCLUSTERED ([POLITICA_DSCTO_PROMO_ID] ASC, [LINEA_ARTICULO_ID] ASC)
);

