CREATE TABLE [dbo].[tbformas_cobro_refer] (
    [ID_FORMA_CBO_REFER]   INT          IDENTITY (1, 1) NOT NULL,
    [FORMA_COBRO_REFER_ID] INT          NOT NULL,
    [FORMA_COBRO_ID]       INT          NOT NULL,
    [NOMBRE]               VARCHAR (30) NOT NULL,
    [REQUERIDA]            CHAR (1)     DEFAULT ('S') NULL,
    [IMPRIMIR_EN_TICKETS]  CHAR (1)     DEFAULT ('S') NULL,
    [IMPRIMIR_EN_REPORTES] CHAR (1)     DEFAULT ('S') NULL,
    [POSICION]             SMALLINT     DEFAULT ('0') NOT NULL,
    [HABILITADA]           CHAR (1)     DEFAULT ('S') NULL,
    [ID_INTERNO]           CHAR (1)     DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdFormaCboRefer] PRIMARY KEY CLUSTERED ([ID_FORMA_CBO_REFER] ASC),
    CONSTRAINT [FORMAS_COBRO_REFER_AK1] UNIQUE NONCLUSTERED ([FORMA_COBRO_ID] ASC, [NOMBRE] ASC)
);

