CREATE TABLE [dbo].[tbgrupos_lineas] (
    [ID_GPO_LIN]           INT          IDENTITY (1, 1) NOT NULL,
    [GRUPO_LINEA_ID]       INT          NOT NULL,
    [NOMBRE]               VARCHAR (50) NOT NULL,
    [CUENTA_ALMACEN]       VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_COSTO_VENTA]   VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_VENTAS]        VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_DEVOL_VENTAS]  VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_COMPRAS]       VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_DEVOL_COMPRAS] VARCHAR (30) DEFAULT (NULL) NULL,
    [ES_PREDET]            CHAR (1)     DEFAULT ('N') NULL,
    [USUARIO_CREADOR]      VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]  DATETIME     NOT NULL,
    [USUARIO_AUT_CREACION] VARCHAR (31) DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]    VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF] DATETIME     NOT NULL,
    [USUARIO_AUT_MODIF]    VARCHAR (31) DEFAULT (NULL) NULL,
    [VISIBLE_EN_WEB]       CHAR (1)     DEFAULT ('S') NULL,
    [INV_CICLICO]          CHAR (1)     DEFAULT ('S') NULL,
    [FECHA_REGISTRO]       DATETIME     DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdGpoLin] PRIMARY KEY CLUSTERED ([ID_GPO_LIN] ASC),
    CONSTRAINT [GRUPOS_LINEAS_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);

