CREATE TABLE [dbo].[tblineas_articulos] (
    [ID_LIN_ART]           INT          IDENTITY (1, 1) NOT NULL,
    [LINEA_ARTICULO_ID]    INT          NOT NULL,
    [NOMBRE]               VARCHAR (50) NOT NULL,
    [GRUPO_LINEA_ID]       INT          DEFAULT (NULL) NULL,
    [CUENTA_ALMACEN]       VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_COSTO_VENTA]   VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_VENTAS]        VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_DEVOL_VENTAS]  VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_COMPRAS]       VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_DEVOL_COMPRAS] VARCHAR (30) DEFAULT (NULL) NULL,
    [ES_PREDET]            CHAR (1)     DEFAULT ('N') NULL,
    [USUARIO_CREADOR]      VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]  DATETIME     NOT NULL,
    [USUARIO_AUT_CREACION] VARCHAR (31) DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]    VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF] DATETIME     NOT NULL,
    [USUARIO_AUT_MODIF]    VARCHAR (31) DEFAULT (NULL) NULL,
    [VISIBLE_EN_WEB]       CHAR (1)     DEFAULT ('S') NULL,
    [INV_CICLICO]          CHAR (1)     DEFAULT ('S') NULL,
    [PUNTOS]               INT          DEFAULT (NULL) NULL,
    [SEGUIMIENTO]          VARCHAR (2)  DEFAULT (NULL) NULL,
    [ID_GRUPO_LIN]         INT          NOT NULL,
    [FECHA_REGISTRO]       DATETIME     DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdLinArt] PRIMARY KEY CLUSTERED ([ID_LIN_ART] ASC),
    CONSTRAINT [LINEAS_ARTICULOS_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [FK_LINEA_GPO_LINEA_idx]
    ON [dbo].[tblineas_articulos]([ID_GRUPO_LIN] ASC);

