CREATE TABLE [dbo].[tbmonedas] (
    [ID_MON]               INT          IDENTITY (1, 1) NOT NULL,
    [MONEDA_ID]            INT          NOT NULL,
    [NOMBRE]               VARCHAR (30) NOT NULL,
    [TEXTO_IMPTE_LETRA]    VARCHAR (30) DEFAULT (NULL) NULL,
    [SIMBOLO]              VARCHAR (10) NOT NULL,
    [ES_MONEDA_LOCAL]      CHAR (1)     DEFAULT ('N') NULL,
    [ES_PREDET]            CHAR (1)     DEFAULT ('N') NULL,
    [USUARIO_CREADOR]      VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]  DATETIME     NOT NULL,
    [USUARIO_AUT_CREACION] VARCHAR (31) DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]    VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF] DATETIME     NOT NULL,
    [USUARIO_AUT_MODIF]    VARCHAR (31) DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdMon] PRIMARY KEY CLUSTERED ([ID_MON] ASC),
    CONSTRAINT [MONEDAS_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);

