CREATE TABLE [dbo].[tbpoliticas_comisiones_vendedores] (
    [ID_POL_COMIS_VEN]      INT            IDENTITY (1, 1) NOT NULL,
    [POLITICA_COMIS_VEN_ID] INT            NOT NULL,
    [NOMBRE]                VARCHAR (50)   NOT NULL,
    [TIPO_CALCULO]          CHAR (1)       NOT NULL,
    [COMISION]              DECIMAL (9, 6) DEFAULT ('0.000000') NOT NULL,
    [ES_PREDET]             CHAR (1)       DEFAULT ('N') NULL,
    [USUARIO_CREADOR]       VARCHAR (31)   DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]   DATETIME       NOT NULL,
    [USUARIO_AUT_CREACION]  VARCHAR (31)   DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]     VARCHAR (31)   DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF]  DATETIME       NOT NULL,
    [USUARIO_AUT_MODIF]     VARCHAR (31)   DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdPolComisVen] PRIMARY KEY CLUSTERED ([ID_POL_COMIS_VEN] ASC),
    CONSTRAINT [POL_COMIS_VEN_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);

