CREATE TABLE [dbo].[tbpoliticas_dsctos_maximos] (
    [ID_POL_DSCTO_MAX]         INT            IDENTITY (1, 1) NOT NULL,
    [POLITICA_DSCTO_MAXIMO_ID] INT            NOT NULL,
    [NOMBRE]                   VARCHAR (50)   NOT NULL,
    [DESCUENTO_MAXIMO]         DECIMAL (9, 6) DEFAULT ('0.000000') NOT NULL,
    [HABILITADA]               CHAR (1)       DEFAULT ('S') NULL,
    [ES_PERMANENTE]            CHAR (1)       DEFAULT ('N') NULL,
    [FECHA_INI_VIGENCIA]       DATE           DEFAULT (NULL) NULL,
    [FECHA_FIN_VIGENCIA]       DATE           DEFAULT (NULL) NULL,
    [USUARIO_CREADOR]          VARCHAR (31)   DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]      VARCHAR (31)   DEFAULT (NULL) NULL,
    [USUARIO_AUT_CREACION]     VARCHAR (31)   DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]        VARCHAR (31)   DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF]     DATETIME       NOT NULL,
    [USUARIO_AUT_MODIF]        VARCHAR (31)   DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdPolDsctoMax] PRIMARY KEY CLUSTERED ([ID_POL_DSCTO_MAX] ASC),
    CONSTRAINT [POLITICAS_DSCTOS_MAXIMOS_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);

