CREATE TABLE [dbo].[tbpoliticas_precios_clientes] (
    [ID_POL_PREC_CLI]           INT          IDENTITY (1, 1) NOT NULL,
    [POLITICA_PRECIOS_CLI_ID]   INT          NOT NULL,
    [NOMBRE]                    VARCHAR (50) NOT NULL,
    [PRECIO_EMPRESA_ID]         INT          NOT NULL,
    [POLITICA_DSCTO_ART_CLI_ID] INT          NOT NULL,
    [HABILITADA]                CHAR (1)     DEFAULT ('S') NULL,
    [ES_PERMANENTE]             CHAR (1)     DEFAULT ('N') NULL,
    [FECHA_INI_VIGENCIA]        DATE         DEFAULT (NULL) NULL,
    [FECHA_FIN_VIGENCIA]        DATE         DEFAULT (NULL) NULL,
    [USUARIO_CREADOR]           VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]       DATETIME     NOT NULL,
    [USUARIO_AUT_CREACION]      VARCHAR (31) DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]         VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF]      DATETIME     NOT NULL,
    [USUARIO_AUT_MODIF]         VARCHAR (31) DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdPolPrecCli] PRIMARY KEY CLUSTERED ([ID_POL_PREC_CLI] ASC),
    CONSTRAINT [POLITICAS_PRECIOS_CLIENTES_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);

