CREATE TABLE [dbo].[tbpoliticas_dsctos_art_cli] (
    [ID_POL_DSCTO_ART_CLI]      INT            IDENTITY (1, 1) NOT NULL,
    [POLITICA_DSCTO_ART_CLI_ID] INT            NOT NULL,
    [NOMBRE]                    VARCHAR (50)   NOT NULL,
    [DESCUENTO]                 DECIMAL (9, 6) DEFAULT ('0.000000') NOT NULL,
    [ES_DSCTO_EXCLUSIVO]        CHAR (1)       DEFAULT ('N') NULL,
    [ES_PREDET]                 CHAR (1)       DEFAULT ('N') NULL,
    [USUARIO_CREADOR]           VARCHAR (31)   DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]       DATETIME       NOT NULL,
    [USUARIO_AUT_CREACION]      VARCHAR (31)   DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]         VARCHAR (31)   DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF]      DATETIME       NOT NULL,
    [USUARIO_AUT_MODIF]         VARCHAR (31)   DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdPolDsctoArtCli] PRIMARY KEY CLUSTERED ([ID_POL_DSCTO_ART_CLI] ASC),
    CONSTRAINT [POLITICAS_DSCTOS_ART_CLI_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);

