CREATE TABLE [dbo].[tbpoliticas_dsctos_promocion] (
    [ID_POL_DSCTO_PROMO]      INT            IDENTITY (1, 1) NOT NULL,
    [POLITICA_DSCTO_PROMO_ID] INT            NOT NULL,
    [NOMBRE]                  VARCHAR (50)   NOT NULL,
    [DESCUENTO]               DECIMAL (9, 6) DEFAULT ('0.000000') NOT NULL,
    [ES_DSCTO_EXCLUSIVO]      CHAR (1)       DEFAULT ('N') NULL,
    [HABILITADA]              CHAR (1)       DEFAULT ('S') NULL,
    [ES_PERMANENTE]           CHAR (1)       DEFAULT ('N') NULL,
    [FECHA_INI_VIGENCIA]      DATETIME       DEFAULT (NULL) NULL,
    [FECHA_FIN_VIGENCIA]      DATETIME       DEFAULT (NULL) NULL,
    [APLICAR_HORARIO]         CHAR (1)       DEFAULT ('N') NULL,
    [HORA_INI]                TIME (7)       DEFAULT (NULL) NULL,
    [HORA_FIN]                TIME (7)       DEFAULT (NULL) NULL,
    [USUARIO_CREADOR]         VARCHAR (31)   DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]     DATETIME       NOT NULL,
    [USUARIO_AUT_CREACION]    VARCHAR (31)   DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]       VARCHAR (31)   DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF]    DATETIME       NOT NULL,
    [USUARIO_AUT_MODIF]       VARCHAR (31)   DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdPolDsctoPromo] PRIMARY KEY CLUSTERED ([ID_POL_DSCTO_PROMO] ASC),
    CONSTRAINT [POLITICAS_DSCTOS_PROMO_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);

