CREATE TABLE [dbo].[tbprecios_cli_zona] (
    [ID_PREC_CLI_ZONA]          INT IDENTITY (1, 1) NOT NULL,
    [PRECIO_CLI_ZONA_ID]        INT NOT NULL,
    [POLITICA_PRECIOS_CLI_ID]   INT NOT NULL,
    [ZONA_CLIENTE_ID]           INT NOT NULL,
    [PRECIO_EMPRESA_ID]         INT NOT NULL,
    [POLITICA_DSCTO_ART_CLI_ID] INT NOT NULL,
    CONSTRAINT [Pk_IdPreCliZona] PRIMARY KEY CLUSTERED ([ID_PREC_CLI_ZONA] ASC),
    CONSTRAINT [PRECIOS_CLI_ZONA_AK1] UNIQUE NONCLUSTERED ([POLITICA_PRECIOS_CLI_ID] ASC, [ZONA_CLIENTE_ID] ASC)
);

