CREATE TABLE [dbo].[tbprecios_cli_tipo] (
    [ID_PRE_CLI_TIP]            INT IDENTITY (1, 1) NOT NULL,
    [PRECIO_CLI_TIPO_ID]        INT NOT NULL,
    [POLITICA_PRECIOS_CLI_ID]   INT NOT NULL,
    [TIPO_CLIENTE_ID]           INT NOT NULL,
    [PRECIO_EMPRESA_ID]         INT NOT NULL,
    [POLITICA_DSCTO_ART_CLI_ID] INT NOT NULL,
    CONSTRAINT [Pk_IdPreCliTip] PRIMARY KEY CLUSTERED ([ID_PRE_CLI_TIP] ASC),
    CONSTRAINT [PRECIOS_CLI_TIPO_AK1] UNIQUE NONCLUSTERED ([POLITICA_PRECIOS_CLI_ID] ASC, [TIPO_CLIENTE_ID] ASC)
);

