CREATE TABLE [dbo].[tbprecios_empresa] (
    [ID_PRE_EMP]        INT           IDENTITY (1, 1) NOT NULL,
    [PRECIO_EMPRESA_ID] INT           NOT NULL,
    [NOMBRE]            VARCHAR (30)  NOT NULL,
    [ID_INTERNO]        CHAR (1)      DEFAULT (NULL) NULL,
    [POSICION]          SMALLINT      DEFAULT ('0') NOT NULL,
    [VISIBLE_EN_WEB]    CHAR (1)      DEFAULT ('S') NULL,
    [LETRA]             CHAR (1)      DEFAULT (NULL) NULL,
    [TITULO_ETIQUETA]   VARCHAR (100) DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdPreEmp] PRIMARY KEY CLUSTERED ([ID_PRE_EMP] ASC),
    CONSTRAINT [PRECIOS_EMPRESA_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);

