CREATE TABLE [dbo].[tbprecios_cli_cli] (
    [ID_PRE_CLI_CLI]            INT          IDENTITY (1, 1) NOT NULL,
    [PRECIO_CLI_CLI_ID]         INT          NOT NULL,
    [POLITICA_PRECIOS_CLI_ID]   INT          NOT NULL,
    [CLAVE_CLIENTE]             VARCHAR (20) DEFAULT (NULL) NULL,
    [CLIENTE_ID]                INT          NOT NULL,
    [PRECIO_EMPRESA_ID]         INT          NOT NULL,
    [POLITICA_DSCTO_ART_CLI_ID] INT          NOT NULL,
    CONSTRAINT [Pk_IdPreCliCli] PRIMARY KEY CLUSTERED ([ID_PRE_CLI_CLI] ASC),
    CONSTRAINT [PRECIOS_CLI_CLI_AK1] UNIQUE NONCLUSTERED ([POLITICA_PRECIOS_CLI_ID] ASC, [CLIENTE_ID] ASC)
);

