CREATE TABLE [dbo].[tbroles_claves_articulos] (
    [ID_ROL_CVE_ART]       INT          IDENTITY (1, 1) NOT NULL,
    [ROL_CLAVE_ART_ID]     INT          NOT NULL,
    [NOMBRE]               VARCHAR (50) NOT NULL,
    [ES_PPAL]              CHAR (1)     DEFAULT ('N') NULL,
    [ES_GTIN]              CHAR (1)     DEFAULT ('N') NULL,
    [USUARIO_CREADOR]      VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]  DATETIME     NOT NULL,
    [USUARIO_AUT_CREACION] VARCHAR (31) DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]    VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF] DATETIME     NOT NULL,
    [USUARIO_AUT_MODIF]    VARCHAR (31) DEFAULT (NULL) NULL,
    CONSTRAINT [Pk_IdRolCveArt] PRIMARY KEY CLUSTERED ([ID_ROL_CVE_ART] ASC),
    CONSTRAINT [ROLES_CLAVES_ART_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);

