CREATE TABLE [dbo].[tbtipos_clientes] (
    [ID_TIPO_CLI]          INT          IDENTITY (1, 1) NOT NULL,
    [TIPO_CLIENTE_ID]      INT          NOT NULL,
    [NOMBRE]               VARCHAR (50) NOT NULL,
    [CUENTA_CXC]           VARCHAR (30) DEFAULT (NULL) NULL,
    [CUENTA_ANTICIPOS]     VARCHAR (30) DEFAULT (NULL) NULL,
    [ES_PREDET]            CHAR (1)     DEFAULT ('N') NULL,
    [USUARIO_CREADOR]      VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_CREACION]  DATETIME     NOT NULL,
    [USUARIO_AUT_CREACION] VARCHAR (31) DEFAULT (NULL) NULL,
    [USUARIO_ULT_MODIF]    VARCHAR (31) DEFAULT (NULL) NULL,
    [FECHA_HORA_ULT_MODIF] DATETIME     NOT NULL,
    [USUARIO_AUT_MODIF]    VARCHAR (31) DEFAULT (NULL) NULL,
    [VISIBLE_EN_WEB]       CHAR (1)     DEFAULT ('S') NULL,
    CONSTRAINT [Pk_IdTipoCli] PRIMARY KEY CLUSTERED ([ID_TIPO_CLI] ASC),
    CONSTRAINT [TIPOS_CLIENTES_AK1] UNIQUE NONCLUSTERED ([NOMBRE] ASC)
);

